---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: my-ingress
spec:
  rules:
  - host: <master_ip>.nip.io
    http:
      paths:
      - backend:
          serviceName: my-service
          servicePort: 80
